# Generated by Django 3.2.6 on 2021-08-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='id',
            new_name='variant_id',
        ),
    ]
