# Generated by Django 3.2.6 on 2021-08-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
