# Generated by Django 3.2.6 on 2021-09-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_variant_variant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='variant_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
