# Generated by Django 3.2.6 on 2021-08-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210822_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='popular_variant_index',
        ),
    ]
